[package]
name = "curly_bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.48"
proc-macro2 = "1.0.69"
regex = "1.10.2"
convert_case = "0.6.0"
